# Generated by Django 4.1.3 on 2022-12-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0003_alter_brandoffer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_offer',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='BrandOffer',
        ),
    ]
