# Generated by Django 4.1.3 on 2022-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0004_brand_brand_offer_delete_brandoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_offer',
            field=models.IntegerField(default=0),
        ),
    ]
