# Generated by Django 4.1.3 on 2022-12-01 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0007_remove_coupon_discount_remove_coupon_min_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_value',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
