# Generated by Django 4.1.3 on 2022-12-01 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0008_alter_coupon_offer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_value',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
