# Generated by Django 4.1.3 on 2022-12-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0011_couponuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuser',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
