# Generated by Django 4.1.3 on 2022-12-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0012_couponuser_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_offer',
        ),
    ]
