# Generated by Django 4.1.3 on 2022-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0014_alter_couponuser_coupon_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Brand_img',
            field=models.ImageField(upload_to='photos/brand'),
        ),
    ]
