# Generated by Django 4.1.3 on 2022-11-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productimage_product'),
        ('store', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
