# Generated by Django 4.1.3 on 2022-12-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='prouduct',
            new_name='product',
        ),
    ]
