# Generated by Django 4.1.3 on 2022-11-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('Category_img', models.ImageField(blank=True, upload_to='photos/Category')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'catergory',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
