# Generated by Django 4.1.3 on 2022-11-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
