# Generated by Django 4.1.3 on 2022-11-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_is_acitve_ram_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ram',
            old_name='is_active',
            new_name='is_acitve',
        ),
    ]
