# Generated by Django 4.1.3 on 2022-12-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_color_category_name_remove_ram_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(default=0),
        ),
    ]
