# Generated by Django 4.1.3 on 2022-12-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_products_size'),
        ('category', '0009_alter_category_category_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
