# Generated by Django 4.1.3 on 2023-07-25 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("address_2", models.TextField()),
                ("state", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("pincode", models.IntegerField()),
                ("total_price", models.IntegerField()),
                ("payment_mode", models.CharField(max_length=150)),
                ("payment_id", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Order confirmed", "Order confirmed"),
                            ("Shipped", "Shipped"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Completed", "Completed"),
                            ("Order cancelled", "Order cancelled"),
                            ("Returned", "Returned"),
                        ],
                        default="Order confirmed",
                        max_length=200,
                    ),
                ),
                ("tracking_no", models.CharField(max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="successordermod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=150, null=True)),
                ("status", models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="useraddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="you name")),
                ("mobile", models.CharField(default="1", max_length=32)),
                ("email", models.CharField(default="1", max_length=140)),
                ("address", models.CharField(max_length=1024)),
                ("address_2", models.CharField(blank=True, max_length=1024, null=True)),
                ("city", models.CharField(max_length=256)),
                ("district", models.CharField(max_length=256)),
                ("state", models.CharField(max_length=256)),
                ("pincode", models.CharField(max_length=6)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Address",
            },
        ),
        migrations.CreateModel(
            name="ReviewRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=50)),
                ("review", models.TextField(blank=True, max_length=500)),
                ("rating", models.FloatField()),
                ("ip", models.CharField(blank=True, max_length=20)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productattribute",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("comment", models.CharField(max_length=256)),
                (
                    "item_img",
                    models.ImageField(max_length=256, upload_to="photos/return"),
                ),
                (
                    "Order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returnReason",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderelate",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderproduct",
                        to="products.products",
                    ),
                ),
            ],
        ),
    ]
