# Generated by Django 4.1.3 on 2022-11-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_alter_order_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Recieved wrong Item', 'Recieved wrong Item'), ('Damaged Product', 'Damaged Product'), ("Don't like the color of the Product", "Don't like the color of the Product"), ('Quality of the product not as expected', 'Quality of the product not as expected'), ('Product missing in the Packet', 'Product missing in the Packet')], max_length=200)),
                ('comment', models.CharField(max_length=256)),
                ('item_img', models.ImageField(max_length=256, upload_to='photos/return')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
