# Generated by Django 4.1.3 on 2022-11-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_return_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='user',
        ),
    ]
