# Generated by Django 4.1.3 on 2022-12-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_return_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnReason', to='orders.order'),
        ),
    ]
