# Generated by Django 4.1.3 on 2022-12-07 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_productattribute_product_offer_and_more'),
        ('orders', '0015_alter_return_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='products.products'),
        ),
    ]
