# Generated by Django 4.1.3 on 2022-12-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='product',
        ),
    ]
