# Generated by Django 4.1.3 on 2022-12-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_productattribute_product_offer_and_more'),
        ('orders', '0019_remove_reviewrating_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute'),
        ),
    ]
