# Generated by Django 4.1.3 on 2022-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_reviewrating_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='successordermod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
