# Generated by Django 4.1.3 on 2022-11-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Memory', 'Memory'), ('Color', 'Color')], max_length=200),
        ),
    ]
