# Generated by Django 4.1.3 on 2022-11-16 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_size'),
        ('products', '0009_delete_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Product_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_img2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_img3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_subcategory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.color'),
        ),
        migrations.AddField(
            model_name='products',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.ram'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute'),
        ),
    ]
