# Generated by Django 4.1.3 on 2022-11-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productattribute_description_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photos/Category'),
        ),
    ]
