# Generated by Django 4.1.3 on 2022-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(max_length=256, upload_to='photos/product'),
        ),
    ]
