# Generated by Django 4.1.3 on 2022-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_productattribute_product_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='product_offer',
            field=models.IntegerField(default=0),
        ),
    ]
