# Generated by Django 4.1.3 on 2022-12-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_productattribute_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_offer',
        ),
    ]
