# Generated by Django 4.1.3 on 2022-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_remove_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='image_2',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photos/product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image_3',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(max_length=256, null=True, upload_to='photos/product'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
