# Generated by Django 4.1.3 on 2022-12-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_productattribute_image_2_productattribute_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product'),
        ),
    ]
